apiVersion: apps/v1
kind: Deployment
metadata:
  name: mnist-ray-tune
  labels:
    app: mnist-ray-tune
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mnist-ray-tune
  template:
    metadata:
      labels:
        app: mnist-ray-tune
    spec:
      containers:
        - name: mnist-ray-tune
          image: mnist-ray-tune:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8265
          volumeMounts:
            - name: env-file
              mountPath: /app/.env
              subPath: .env
          resources:
            requests:
              cpu: "1"
              memory: "1.5Gi"
            limits:
              cpu: "1"
              memory: "2Gi"
      volumes:
        - name: env-file
          secret:
            secretName: my-env-secret
