apiVersion: v1
kind: Service
metadata:
  name: mnist-ray-tune-service
spec:
  type: NodePort
  selector:
    app: mnist-ray-tune
  ports:
    - protocol: TCP
      port: 8265
      targetPort: 8265
      nodePort: 30000
