name: CI

on:
  push:
    branches: [ '**' ]

jobs:
  test-and-smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8

      - name: Lint
        run: flake8 .

      - name: Run unit tests
        run: pytest -q

      - name: Build & smoke‑run Docker
        run: |
          docker build -t dqn:test .
          docker run --rm dqn:test --actors 1 --episodes 1000 --wave 100

  docker-push:
    needs: test-and-smoke
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & push
        run: |
          docker build -t your-dockerhub-username/dqn:${GITHUB_SHA::8} .
          docker push your-dockerhub-username/dqn:${GITHUB_SHA::8}
