apiVersion: ray.io/v1
kind: RayCluster
metadata:
  name: dqn-local
spec:
  rayVersion: "2.5.0"
  headGroupSpec:
    rayStartParams: { dashboard-host: "0.0.0.0" }
    template:
      spec:
        containers:
          - name: ray-head
            image: dqn:test
            resources:
              limits: { cpu: "1" }
  workerGroupSpecs:
    - replicas: 1
      minReplicas: 1
      maxReplicas: 1
      rayStartParams: {}
      template:
        spec:
          containers:
            - name: ray-worker
              image: dqn:test
              resources:
                limits: { cpu: "1" }
